# Generated by Django 5.0 on 2024-06-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid_name', models.CharField(max_length=100)),
                ('vid_sec_length', models.BigIntegerField()),
                ('vid_key', models.CharField(max_length=11)),
            ],
        ),
    ]
