# Generated by Django 5.0 on 2024-06-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteFace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videostorage',
            name='vid_extracted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videostorage',
            name='vid_key',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
