# Generated by Django 5.0 on 2024-06-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteFace', '0002_videostorage_vid_extracted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videostorage',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
