# Generated by Django 5.0 on 2024-06-24 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websiteFace', '0003_videostorage_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videostorage',
            name='name',
        ),
    ]
