# Generated by Django 5.0 on 2024-06-24 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteFace', '0006_rename_teamfound_resultstorage_found'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultstorage',
            name='found',
            field=models.CharField(max_length=100),
        ),
    ]
