# Generated by Django 5.0 on 2024-06-28 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='club',
            name='advisorOrAdvisors',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='club',
            name='contact',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='club',
            name='generalMeets',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='club',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
