# Generated by Django 5.0 on 2024-06-28 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_club_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='url',
            field=models.URLField(blank=True, max_length=150, null=True),
        ),
    ]
