# Generated by Django 5.0 on 2024-06-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_club_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='tagOrTags',
            field=models.ManyToManyField(blank=True, to='users.clubtag'),
        ),
        migrations.AlterField(
            model_name='club',
            name='users',
            field=models.ManyToManyField(blank=True, to='users.user'),
        ),
    ]
