# Generated by Django 5.0.6 on 2024-06-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_club_tagortags_alter_club_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='homeURL',
            field=models.URLField(blank=True, max_length=150, null=True),
        ),
    ]
