# Generated by Django 5.0.6 on 2024-07-05 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_extradata_user_picurl'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
