# Generated by Django 5.0.6 on 2024-07-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_user_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='advisors',
            field=models.ManyToManyField(blank=True, related_name='club_advisors', to='users.users'),
        ),
        migrations.AlterField(
            model_name='club',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='club_users', to='users.users'),
        ),
    ]
