# Generated by Django 5.0.6 on 2024-07-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_club_advisors_alter_club_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='leaders',
            field=models.ManyToManyField(blank=True, related_name='club_leaders', to='users.users'),
        ),
    ]
