# Generated by Django 5.0.6 on 2024-07-27 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_livefeed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livefeed',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='op', to='users.users'),
        ),
    ]
