# Generated by Django 5.0.6 on 2024-07-28 00:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_livefeed_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='livefeed',
            name='creationTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='livefeed',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
