# Generated by Django 5.0.6 on 2024-08-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_livefeed_creationtime_livefeed_edited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='homeURL',
        ),
        migrations.AddField(
            model_name='club',
            name='Picture URL',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='frontPage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='memberPage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='picURL',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
