# Generated by Django 5.0.6 on 2024-08-07 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_club_homeurl_club_picture_url_club_frontpage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='Picture URL',
            new_name='homeURL',
        ),
    ]
