# Generated by Django 5.0.6 on 2024-08-07 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_livefeed_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='livefeed',
            name='comments',
            field=models.IntegerField(default=0),
        ),
    ]
