# Generated by Django 5.0.6 on 2024-08-08 07:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_livefeed_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livefeed',
            name='text',
            field=models.TextField(blank=True, max_length=24000, null=True),
        ),
        migrations.CreateModel(
            name='Replies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=3750, null=True)),
                ('edited', models.BooleanField(default=False)),
                ('creationTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('linkToOtherReply', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ReplyOp', to='users.users')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OriginalPost', to='users.livefeed')),
            ],
        ),
    ]
