# Generated by Django 5.0.6 on 2024-08-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_replies_replylink'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='applicationInfo',
            field=models.TextField(blank=True),
        ),
    ]
