# Generated by Django 5.0.6 on 2025-03-17 08:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_clubdata_creationtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livefeed',
            name='creationTime',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
